# Site settings
title: Futouris
client:
  name: F체r die Umwelt
  link: "https://www.futouris.org/"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Urlaubsl채nder bewahren und die Reisebranche zukunftsf채hig gestalten - daf체r steht die Nachhaltigkeitsinitiative Futouris e.V..

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/futouris" # the subpath of your site, e.g. /blog/
img:     "/de/futouris/_assets/img"
css:     "/de/futouris/_assets/css"
js:      "/de/futouris/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
